package cn.com.jit.ida.ca.certmanager;

import cn.com.jit.ida.IDAException;

public class CertException extends IDAException
{
  public static final String CA = "80";
  public static final String RAToolkit = "81";
  public static final String CERT_REQUEST = "8001";
  public static final String CERT_REQUEST_DES = "证书申请服务";
  public static final String CERT_DOWNLOAD = "8002";
  public static final String CERT_DOWNLOAD_DES = "证书下载服务";
  public static final String CERT_REQDOWN = "8003";
  public static final String CERT_REQDOWN_DES = "证书申请并下载服务";
  public static final String CERT_REVOKE = "8004";
  public static final String CERT_REVOKE_DES = "证书注销服务";
  public static final String CERT_HOLD = "8005";
  public static final String CERT_HOLD_DES = "证书冻结服务";
  public static final String CERT_UNHOLD = "8006";
  public static final String CERT_UNHOLD_DES = "证书解冻服务";
  public static final String CERT_QUERY = "8007";
  public static final String CERT_QUERY_DES = "证书查询服务";
  public static final String CERT_ENTITY_QUERY = "8008";
  public static final String CERT_ENTITY_QUERY_DES = "证书实体查询服务";
  public static final String CERT_UPDATE = "8009";
  public static final String CERT_UPDATE_DES = "证书更新服务";
  public static final String CERT_UPDDOWN = "8011";
  public static final String CERT_UPDDOWN_DES = "证书更新并下载服务";
  public static final String AUTHCODE_UPDATE = "8012";
  public static final String AUTHCODE_UPDATE_DES = "授权码更新服务";
  public static final String CRL_QUERY = "8013";
  public static final String CRL_QUERY_DES = "CRL查询服务";
  public static final String CERT_KEYRECOVER = "8014";
  public static final String CERT_KEYRECOVER_DES = "密钥恢复服务";
  public static final String RATK_CERT_REQUEST = "8101";
  public static final String RATK_CERT_REQUEST_DES = "证书申请服务";
  public static final String RATK_CERT_DOWNLOAD = "8102";
  public static final String RATK_CERT_DOWNLOAD_DES = "证书下载服务";
  public static final String RATK_CERT_REQDOWN = "8103";
  public static final String RATK_CERT_REQDOWN_DES = "证书申请并下载服务";
  public static final String RATK_CERT_REVOKE = "8104";
  public static final String RATK_CERT_REVOKE_DES = "证书注销服务";
  public static final String RATK_CERT_HOLD = "8105";
  public static final String RATK_CERT_HOLD_DES = "证书冻结服务";
  public static final String RATK_CERT_UNHOLD = "8106";
  public static final String RATK_CERT_UNHOLD_DES = "证书解冻服务";
  public static final String RATK_CERT_QUERY = "8107";
  public static final String RATK_CERT_QUERY_DES = "证书查询服务";
  public static final String RATK_CERT_ENTITY_QUERY = "8108";
  public static final String RATK_CERT_ENTITY_QUERY_DES = "证书实体查询服务";
  public static final String RATK_CERT_UPDATE = "8109";
  public static final String RATK_CERT_UPDATE_DES = "证书更新服务";
  public static final String RATK_CERT_UPDDOWN = "8111";
  public static final String RATK_CERT_UPDDOWN_DES = "证书更新并下载服务";
  public static final String RATK_AUTHCODE_UPDATE = "8112";
  public static final String RATK_AUTHCODE_UPDATE_DES = "授权码更新服务";
  public static final String RATK_CRL_QUERY = "8113";
  public static final String RATK_CRL_QUERY_DES = "CRL查询服务";
  public static final String RATK_CERT_KEYRECOVER = "8114";
  public static final String RATK_CERT_KEYRECOVER_DES = "密钥恢复服务";
  public static final String LICENCE_ERR = "01";
  public static final String LICENCE_ERR_DES = "Licence验证 ";
  public static final String VALIDATE_ERR = "02";
  public static final String VALIDATE_ERR_DES = "数据有效性检查 ";
  public static final String POLICY_ERR = "03";
  public static final String POLICY_ERR_DES = "操作员权限检查 ";
  public static final String STATUS_ERR = "04";
  public static final String STATUS_ERR_DES = "证书状态检查 ";
  public static final String CTML_ERR = "05";
  public static final String CTML_ERR_DES = "模板策略检查 ";
  public static final String DEAL_OPERATION_ERR = "06";
  public static final String DEAL_OPERATION_ERR_DES = "执行业务操作 ";
  public static final String OTHERS_ERR = "07";
  public static final String OTHERS_ERR_DES = "其他错误 ";
  public static final String REQUEST = "08";
  public static final String REQUEST_DES = "设置申请信息错误 ";
  public static final String REPONSE = "09";
  public static final String RESPONSE_DES = "设置响应信息错误";
  public static final String OPTOR_NULL = "0701";
  public static final String OPTOR_NULL_DES = "其他错误 操作员为空";
  public static final String OPTOR_DN_NULL = "0702";
  public static final String OPTOR_DN_NULL_DES = "其他错误 操作员DN为空";
  public static final String OPTLOG_ERR = "0703";
  public static final String OPTLOG_ERR_DES = "其他错误 记录业务日志失败";
  public static final String REQ_FORMAT_ERR = "0704";
  public static final String REQ_FORMAT_ERR_DES = "其他错误 请求信息格式不合法";
  public static final String REP_FORMAT_ERR = "0705";
  public static final String REP_FORMAT_ERR_DES = "其他错误 应答信息格式不合法";
  public static final String SYS_ERR = "0706";
  public static final String SYS_ERR_DES = "其他错误 系统错误";
  public static final String KMC_RECOVER_ERR = "0707";
  public static final String KMC_RECOVER_ERR_DES = "其他错误 从KMC恢复密钥失败";
  public static final String DB_ERR = "0708";
  public static final String DB_ERR_DES = "其他错误 DB错误";
  public static final String REQ_DN_ERR = "0801";
  public static final String REQ_DN_ERR_DES = "设置申请信息错误 证书主题内容错误";
  public static final String REQ_CTML_ERR = "0802";
  public static final String REQ_CTML_ERR_DES = "设置申请信息错误 模板名称内容错误";
  public static final String REQ_NOTBEFORE_ERR = "0803";
  public static final String REQ_NOTBEFORE_ERR_DES = "设置申请信息错误 起始有效期内容错误";
  public static final String REQ_VALIDITY_ERR = "0804";
  public static final String REQ_VALIDITY_ERR_DES = "设置申请信息错误 有效期长度内容错误";
  public static final String REQ_REF_CODE_ERR = "0805";
  public static final String REQ_REF_CODE_ERR_DES = "设置申请信息错误 参考号内容错误";
  public static final String REQ_AUTH_CODE_ERR = "0806";
  public static final String REQ_AUTH_CODE_ERR_DES = "设置申请信息错误 授权码内容错误";
  public static final String REQ_SN_ERR = "0807";
  public static final String REQ_SN_ERR_DES = "设置申请信息错误 证书序列号内容错误";
  public static final String LICENCE_NUM_ERR = "0101";
  public static final String LICENCE_NUM_ERR_DES = "Licence验证 超出Licence发证量限制";
  public static final String LICENCE_DATE_ERR = "0102";
  public static final String LICENCE_DATE_ERR_DES = "Licence验证 超出Licence有效期限制";
  public static final String LICENCE_GET_ERR = "0103";
  public static final String LICENCE_GET_ERR_DES = "Licence验证 获取Licence信息异常";
  public static final String LICENCE_VALIDNUM_ERR = "0104";
  public static final String LICENCE_VALIDNUM_ERR_DES = "Licence验证 超出Licence有效证书量限制";
  public static final String SN_NULL_ERR = "0201";
  public static final String SN_NULL_ERR_DES = "数据有效性检查 证书序列号为空";
  public static final String DN_NULL_ERR = "0202";
  public static final String DN_NULL_ERR_DES = "数据有效性检查 证书主题为空";
  public static final String DN_LENGTH_ERR = "0203";
  public static final String DN_LENGTH_ERR_DES = "数据有效性检查 证书主题长度过长";
  public static final String DN_FORMAT_ERR = "0204";
  public static final String DN_FORMAT_ERR_DES = "数据有效性检查 证书主题格式不合法";
  public static final String CTML_NULL_ERR = "0205";
  public static final String CTML_NULL_ERR_DES = "数据有效性检查 证书模板为空";
  public static final String NOTBEFORE_NULL_ERR = "0206";
  public static final String NOTBEFORE_NULL_ERR_DES = "数据有效性检查 有效期起始日期为空";
  public static final String NOTBEFORE_LENGTH_ERR = "0207";
  public static final String NOTBEFORE_LENGTH_ERR_DES = "数据有效性检查 有效期起始日期长度错误";
  public static final String NOTBEFORE_DIFTIME_ERR = "0208";
  public static final String NOTBEFORE_DIFTIME_ERR_DES = "数据有效性检查 有效期起始日期超出服务允许范围";
  public static final String NOTBEFORE_PARSE_ERR = "0209";
  public static final String NOTBEFORE_PARSE_ERR_DES = "数据有效性检查 有效期起始日期格式格式不合法";
  public static final String VALIDATE_NULL_ERR = "0210";
  public static final String VALIDATE_NULL_ERR_DES = "数据有效性检查 有效期天数为空";
  public static final String VALIDITY_PARSE_ERR = "0211";
  public static final String VALIDITY_PARSE_ERR_DES = "数据有效性检查 有效期格式不合法";
  public static final String VALIDATE_VALUE_ERR = "0212";
  public static final String VALIDATE_VALUE_ERR_DES = "数据有效性检查 有效天数小于0";
  public static final String CERT_ALREADY_EXISTS = "0213";
  public static final String CERT_ALREADY_EXISTS_DES = "数据有效性检查 证书已存在，申请无效";
  public static final String REFCODE_NULL_ERR = "0214";
  public static final String REFCODE_NULL_ERR_DES = "数据有效性检查 参考号为空";
  public static final String REFCODE_FORMAT_ERR = "0215";
  public static final String REFCODE_FORMAT_ERR_DES = "数据有效性检查 参考号位数超长";
  public static final String AUTHCODE_NULL_ERR = "0216";
  public static final String AUTHCODE_NULL_ERR_DES = "数据有效性检查 授权码必须非空";
  public static final String AUTHCODE_FORMAT_ERR = "0217";
  public static final String AUTHCODE_FORMAT_ERR_DES = "数据有效性检查 授权码位数超长";
  public static final String P10_NULL_ERR = "0218";
  public static final String P10_NULL_ERR_DES = "数据有效性检查 P10申请书必须非空";
  public static final String CTML_LEN_ERR = "0219";
  public static final String CTML_LEN_ERR_DES = "数据有效性检查 模板名称超长";
  public static final String EMAIL_LEN_ERR = "0220";
  public static final String EMAIL_LEN_ERR_DES = "数据有效性检查 e-mail内容超长";
  public static final String REMARK_LEN_ERR = "0221";
  public static final String REMARK_LEN_ERR_DES = "数据有效性检查 备注信息内容超长";
  public static final String VALDITY_LEN_ERR = "0222";
  public static final String VALDITY_LEN_ERR_DES = "数据有效性检查 有效期长度内容超长";
  public static final String AUTHCODE_VALUE_ERR = "0223";
  public static final String AUTHCODE_VALUE_ERR_DES = "数据有效性检查 授权码不正确";
  public static final String OVER_ROOTCERT_VALIDATE_ERR = "0224";
  public static final String OVER_ROOTCERT_VALIDATE_ERR_DES = "数据有效性检查 证书终止有效期超过CA签名证书有效期";
  public static final String RVK_DES_OVER_LEN_ERR = "0225";
  public static final String RVK_DES_OVER_LEN_ERR_DES = "数据有效性检查 注销证书原因描述的长度超长";
  public static final String HOLD_DES_OVER_LEN_ERR = "0226";
  public static final String HOLD_DES_OVER_LEN_ERR_DES = "数据有效性检查 冻结证书原因描述的长度超长";
  public static final String AUTHCODE_VALID_ERR = "0227";
  public static final String AUTHCODE_VALID_ERR_DES = "数据有效性检查 该授权码已超出使用有效期";
  public static final String NOT_ENOUGH_REQ = "0228";
  public static final String NOT_ENOUGH_REQ_DES = "数据有效性检查 证书序列号为空时，证书主题和证书模板不能为空";
  public static final String CERT_NULL_ERR = "0229";
  public static final String CERT_NULL_ERR_DES = "数据有效性检查 证书不存在";
  public static final String NO_RECORD_DN_CTML_ERR = "0230";
  public static final String NO_RECORD_DN_CTML_ERR_DES = "数据有效性检查 根据[证书主题+模板名称]条件没有查询到待操作记录";
  public static final String NO_RECORD_SN_ERR = "0231";
  public static final String NO_RECORD_SN_ERR_DES = "数据有效性检查 根据SN没有查询到记录";
  public static final String QUERY_FROM_NULL = "0232";
  public static final String QUERY_FROM_NULL_DES = "数据有效性检查 查询证书信息，查询起始位置为空";
  public static final String QUERY_COUNT_NULL = "0233";
  public static final String QUERY_COUNT_NULLDES = "数据有效性检查 查询证书信息，查询数量为空";
  public static final String ADMIN_SELF_OPT_ERR = "0234";
  public static final String ADMIN_SELF_OPT_ERR_DES = "数据有效性检查 禁止管理员对本身进行操作";
  public static final String REP_CONDITION_NOTVALIDATE = "0235";
  public static final String REP_CONDITION_NOTVALIDATE_DES = "数据有效性检查 欲恢复密钥的检索条件不正确";
  public static final String COMPARETIME_LENGTH_ERR = "0236";
  public static final String COMPARETIME_LENGTH_ERR_DES = "数据有效性检查 时间点日期长度错误";
  public static final String CERT_STATUS_ERR = "0401";
  public static final String CERT_STATUS_ERR_DES = "证书状态检查 证书状态非法";
  public static final String CERT_STATUS_REQ_DES = "此证书已存在并处于使用状态，请重新确认申请信息";
  public static final String CERT_STATUS_UPD_DES = "此证书未处于使用状态，无法完成更新操作";
  public static final String CERT_STATUS_CODE_UPD_DES = "证书已被下载使用，无法完成授权码更新操作";
  public static final String CERT_STATUS_DOWN_DES = "证书已被下载使用,无法完成下载操作";
  public static final String CERT_STATUS_HOLD_DES = "此证书未处于使用状态，无法完成冻结操作";
  public static final String CERT_STATUS_REVOKE_DES = "此证书已被注销，无法完成注销操作";
  public static final String CERT_STATUS_UNHOLD_DES = "此证书未处于冻结状态,无法完成解冻操作";
  public static final String POLICY_CHECK_ERR = "0301";
  public static final String POLICY_CHECK_ERR_DES = "操作员权限检查 操作员业务权限检查失败";
  public static final String SELF_OPERATION_ERR = "0302";
  public static final String SELF_OPERATION_ERR_DES = "操作员权限检查 操作员没有自操作权限";
  public static final String NO_POLICY_QUERY_CTML = "0303";
  public static final String NO_POLICY_QUERY_CTML_DES = "操作员权限检查 操作员没有待操作模板的查询权限";
  public static final String POLICY_NO_POLICY_FOR = "操作员不具备此操作权限，请检查操作员是否有操作此模板的权限，并且确保证书DN符合管理员权限范围";
  public static final String CTML_STATUS_ERR = "0501";
  public static final String CTML_STATUS_ERR_DES = "模板策略检查 证书模板状态无效";
  public static final String CTML_MAXVALIDATE_ERR = "0502";
  public static final String CTML_MAXVALIDATE_ERR_DES = "模板策略检查 超出证书模板允许有效期的最大效期";
  public static final String CTML_NOTAFTER_ERR = "0503";
  public static final String CTML_NOTAFTER_ERR_DES = "模板策略检查 超出模板有效期范围";
  public static final String CTML_EXT_VALUE_ERR = "0504";
  public static final String CTML_EXT_VALUE_ERR_DES = "模板策略检查 必须的扩展域信息不完整";
  public static final String NOTAFTER_MATH_ERR = "0505";
  public static final String NOTAFTER_MATH_ERR_DES = "模板策略检查 计算证书结束时间失败";
  public static final String KEYTYPE_ERR = "0506";
  public static final String KEYTYPE_ERR_DES = "模板策略检查 密钥类型不合法";
  public static final String KEYLENGTH_ERR = "0507";
  public static final String KEYLENGTH_ERR_DES = "模板策略检查 密钥长度不合法";
  public static final String PARSER_CTML_NOTAFTER_ERR = "0508";
  public static final String PARSER_CTML_NOTAFTER_ERR_DES = "模板策略检查 解析模板终止有效期错误";
  public static final String PARSER_CTML_MAXVALIDATE_ERR = "0509";
  public static final String PARSER_CTML_MAXVALIDATE_ERR_DES = "模板策略检查 解析模板最大有效期错误";
  public static final String CTML_STATUS_UPDATE_ERR = "0510";
  public static final String CTML_STATUS_UPDATE_ERR_DES = "模板策略检查 更新证书模板状态失败";
  public static final String NOT_SUPPORT_KMC_ERR = "0511";
  public static final String NOT_SUPPORT_KMC_ERR_DES = "模板策略检查 目前不支持KMC密钥产生方式";
  public static final String SELFEXT_CONTENT_ERR = "0512";
  public static final String SELFEXT_CONTENT_ERR_DES = "模板策略检查 自定义扩展域内容格式不合法";
  public static final String TEMPKEY_NULL_ERR = "0513";
  public static final String TEMPKEY_NULL_ERR_DES = "模板策略检查 未检测到KMC产生密钥所需的临时公钥";
  public static final String REQUIRE_KEYTYPE_NULL_ERR = "0514";
  public static final String REQUIRE_KEYTYPE_NULL_ERR_DES = "模板策略检查 请求密钥类型为空";
  public static final String REQUIRE_KEYLENGTH_NULL_ERR = "0515";
  public static final String REQUIRE_KEYLENGTH_NULL_ERR_DES = "模板策略检查 请求密钥类型为空";
  public static final String KMC_CONN_ERR = "0516";
  public static final String KMC_CONN_ERR_DES = "模板策略检查 与KMCServer通信异常";
  public static final String KMC_REP_ERR = "0517";
  public static final String KMC_REP_ERR_DES = "模板策略检查 向KMC申请密钥失败";
  public static final String STANDARDEXT_CONTENT_ERR = "0518";
  public static final String STANDARDEXT_CONTENT_ERR_DES = "模板策略检查 标准扩展域内容格式不合法";
  public static final String P10_DN_ERR = "0519";
  public static final String P10_DN_ERR_DESC = "模板策略检查 P10申请书DN与待申请证书DN不符";
  public static final String NO_CERT_REVOKE = "0601";
  public static final String NO_CERT_REVOKE_DES = "执行业务操作 没有证书被注销";
  public static final String NO_CERT_HOLD = "0602";
  public static final String NO_CERT_HOLD_DES = "执行业务操作 没有证书被冻结";
  public static final String NO_CERT_UNHOLD = "0603";
  public static final String NO_CERT_UNHOLD_DES = "执行业务操作 没有证书被解冻";
  public static final String NO_AUTHCODE_UPDATE = "0604";
  public static final String NO_AUTHCODE_UPDATE_DES = "执行业务操作 数据库更新授权码操作无效";
  public static final String NO_CERT_DOWNLOAD = "0605";
  public static final String NO_CERT_DOWNLOAD_DES = "执行业务操作 数据库保存证书无效";
  public static final String NO_CERT_REQDOWN = "0606";
  public static final String NO_CERT_REQDOWN_DES = "执行业务操作 数据库执行申请并下载操作无效";
  public static final String NO_CERT_UPDATE = "0607";
  public static final String NO_CERT_UPDATE_DES = "执行业务操作 数据库更新证书无效";
  public static final String NO_CERT_UPDDOWN = "0608";
  public static final String NO_CERT_UPDDOWN_DES = "执行业务操作 数据库执行更新并下载操作无效";
  public static final String SAVE_CROSS_CERT_ERR = "0609";
  public static final String SAVE_CROSS_CERT_ERR_DES = "执行业务操作 保存交叉证书失败";
  public static final String NO_ISSMANAGER = "0610";
  public static final String NO_ISSMANAGER_DES = "执行业务操作 构造发布管理器失败";
  public static final String NULL_RECORD_ERR_DES = "记录不存在";
  public static final String ISS_CERTARC_THREAD_FAILTURE = "后台证书归档操作异常";
  public static final String ISS_CERTARC_THREAD_ERR = "后台业务证书归档操作失败";
  public static final String ISS_CERTARC_THREAD_SUCCESS = "后台证书归档操作成功";
  public static final String ISS_LOGARC_THREAD_FAILTURE = "后台业务日志归档操作异常";
  public static final String ISS_LOGARC_THREAD_ERR = "后台业务日志归档操作失败";
  public static final String ISS_LOGARC_THREAD_SUCCESS = "后台业务日志归档操作成功";
  public static final String ISS_CERT_THREAD_FAILTURE = "后台证书发布操作异常";
  public static final String ISS_CERT_THREAD_FAILTURE_LDAP = "后台发布证书到LDAP异常";
  public static final String ISS_CERT_THREAD_FAILTURE_DISK = "后台发布证书到磁盘异常";
  public static final String ISS_CERT_THREAD_SUCCESS_LDAP = "后台发布证书到LDAP成功";
  public static final String ISS_CERT_THREAD_SUCCESS_DISK = "后台发布证书到磁盘成功";
  public static final String ISS_CERT_THREAD_DELCERT_NOTENOUGH_ERR = "清理操作未完全完成";
  public static final String ISS_CERT_THREAD_DELCERT_ERR = "清理待发布证书记录失败";
  public static final String ISS_CRL_THREAD_FAILTURE = "发布CRL操作异常";
  public static final String ISS_CRL_THREAD_FAILTURE_LDAP = "发布CRL到LDAP异常";
  public static final String ISS_CRL_THREAD_FAILTURE_DISK = "发布CRL到磁盘异常";
  public static final String ISS_CRL_THREAD_FINISH = "发布CRL操作完成";

  public CertException(String paramString)
  {
    super(paramString);
  }

  public CertException(String paramString, Exception paramException)
  {
    super(paramString, paramException);
  }

  public CertException(String paramString1, String paramString2)
  {
    super(paramString1, paramString2);
  }

  public CertException(String paramString1, String paramString2, Exception paramException)
  {
    super(paramString1, paramString2, paramException);
  }
}

/* Location:           C:\Program Files\JIT\CA50\lib\IDA\ida.jar
 * Qualified Name:     cn.com.jit.ida.ca.certmanager.CertException
 * JD-Core Version:    0.6.0
 */